name: AI Code Review
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Allow posting comments on pull requests
      contents: read        # Allow reading the repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debugging - Show current commit
        run: |
          echo "Current commit SHA: $(git rev-parse HEAD)"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Get PR Diff
        id: get-diff
        run: |
          pwd
          mkdir -p diffs
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $FILES"
          for file in $FILES; do
            safe_filename=$(echo "$file" | sed 's/\//_/g')
            git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- "$file" > "diffs/${safe_filename}.diff"
          done

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run AI Review Script
        env:
          API_KEY: ''  # Store your API key in GitHub Secrets
        run: |
          python gemini_review.py

      - name: Post AI Review
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: review
            });
